### ISSUE TITLE
Шапка + Подвал

### ISSUE THREAD

**Issue by danyatochkaru** [piybeep/portfolio-ikt54#2]
* лого
* описание
* ссылки
* копирайт

**Comment by NAVIch0k** [comment]
сделано в ветке 'Страница Проекта'

**Comment by danyatochkaru** [comment]
> сделано в ветке 'Страница Проекта'

нет, Ваня. это уже не в первый раз. я не приму

**Comment by NAVIch0k** [comment]
я не могу прикрепить существующую ветку
